### ISSUE TITLE
Memory leak in inv()

### ISSUE THREAD

**Issue by festlv** [DanielMartensson/CControl#16]
inv() appears to contain two potential memory leaks:
1) one of the temporary variables allocated in inv() is not being freed before returning: https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Sources/LinearAlgebra/inv.c#L28
2) This function has two return statements which bypass freeing the allocated variables.

If you're interested, I can submit a PR for these two issues (which may or may not contain a goto statement :)

**Comment by DanielMartensson** [comment]
Yes. Send a PR. Avoid goto.

**Comment by festlv** [comment]
IMO goto would result in cleaner code, but this is not a hill I'd die on.

**Comment by DanielMartensson** [comment]
Thank you for the pull request.

Yes, I know that goto is very useful. But I have heard that gotos should be avoided due to spelling. 

I see that you have improve som optimization. Great! Thanks. I'm looking forward for more PR from you :) 

![image](https://user-images.githubusercontent.com/28505229/222562269-cc1c74ee-0b1f-4789-a059-acfac5a86eb9.png)
