### ISSUE TITLE
Cat function

### ISSUE THREAD

**Issue by ooaj** [DanielMartensson/CControl#5]
Hello, 

Would you be interested in MATLAB's cat function? I think you already have it implemented in EmbeddedLapack with horzcat and vertcat, but maybe something like ```void cat(int dim, double A[], double B[], double C[], int rowA,
		int colA, int rowB, int colB, int rowC, int colC)``` would be of interest to you akin to MATLAB? 

I already have the implementation (using only memcpy).

**Comment by DanielMartensson** [comment]
> 

Yes! Please do a pull request and also an example.
Notice that this library is using float only. It's because most microcontrollers are not using double. Double float precision is very expensive. But regular single floating precision is more normal.

And one more thing. Try to use `uint16_t` for row/column dimension. `uint8_t` is often used for simple unsigned integers and `uint32_t` is used for very large numbers e.g iterations.

- Float, not double
- Unsigned datatypes, not `int` data type
- Provide with an example

**Comment by ooaj** [comment]
Hey!

Please see https://github.com/DanielMartensson/CControl/pull/6

**Comment by DanielMartensson** [comment]
> Hey!
> 
> Please see #6

Hi!

Yes. I see. I give you a feedback.

**Comment by DanielMartensson** [comment]
Thank you very much. I will try this out now.
