### ISSUE TITLE
Inverse of a matrix fails

### ISSUE THREAD

**Issue by ooaj** [DanielMartensson/CControl#9]
Hi,

The status of a square matrix, even though the determinant is `0`, equals to `1`.  For example, consider 

```
float A[2 * 2] = {1, 1, 1, 1};
int status = inv(A, 2);
printf("status is: %d\n", status);
print(A, 2, 2);
```

In this case, `status` is `1` while it should be `0`. The resultant matrix is all `Inf`s as in MATLAB.

**Comment by DanielMartensson** [comment]
> 

Can you write out what the value is at this line

https://github.com/DanielMartensson/CControl/blob/5510477b1ba1a24b075c48fa7a6078df3dd4cec9/src/CControl/Sources/LinearAlgebra/lup.c#L40

When `lup.c` file returns 0, then the `inv.c` returns 0 as well. 

Edit:

I did a quick check. I found the issue

``` 
/*
 ============================================================================
 Name        : inv.c
 Author      : Daniel Mårtensson
 Version     : 1.0
 Copyright   : MIT
 Description : Turn A into inverse A^(-1)
 ============================================================================
 */

#include "CControl/Headers/Functions.h"

int main() {

	// Matrix A
	float A[2*2] = {1, 1, 1, 1};

	clock_t start, end;
	float cpu_time_used;
	start = clock();
	int status = inv(A, 2);
	printf("Status on matrix A(1 == success, 0 == fail): %d\n", status);
	end = clock();
	cpu_time_used = ((float) (end - start)) / CLOCKS_PER_SEC;
	printf("\nTotal speed  was %f\n", cpu_time_used);

	// Print A
	printf("A^(-1)\n");
	print(A, 2, 2);

	return EXIT_SUCCESS;
}
```

Output:

```
Status on matrix A(1 == success, 0 == fail): 1

Total speed  was 0.000000
A^(-1)
1.#INF00000000000000	-1.#INF00000000000000	
-1.#INF00000000000000	1.#INF00000000000000	
```

The issue is here:
Question: Can you be so kind to do an if-statement and check if we are dividing with `0` ? If we are dividing with zero, then the static function should return `uint8_t` or `bool` as `0` or `false`. As a check only. Can you do this? Send me then a pull request?

https://github.com/DanielMartensson/CControl/blob/5510477b1ba1a24b075c48fa7a6078df3dd4cec9/src/CControl/Sources/LinearAlgebra/inv.c#L68


Edit:

I have fixed the issue.
Please re-open the issue if the issue still occurs.

**Comment by ooaj** [comment]
Aha. Great! Thanks @DanielMartensson. Works perfectly now.

**Comment by DanielMartensson** [comment]
> Aha. Great! Thanks @DanielMartensson. Works perfectly now.

Thank you @ooaj for finding this issue.
If you want, you could help me implement a Kernel Density Estimation algorithm. It's very easy.

Here is the formula:
![image](https://user-images.githubusercontent.com/28505229/149302701-4238008c-2412-4482-a472-5f4e8888a57f.png)

K is the gaussian propability density function.

https://en.wikipedia.org/wiki/Kernel_density_estimation#Definition

The theory: See between 0:0 to 2:00 https://www.youtube.com/watch?v=DCgPRaIDYXA&t=1s&ab_channel=KimberlyFessel

Assume that you have a mesurement `float my_measurement[100]` and you want to find the correct value, because it's a nonlinear measurement. If you plot `float my_measurement[100]` you can see two gaussian curves, but which one should you select? Just use KDE algorithm as above. 

Can you do that?

**Comment by ooaj** [comment]
Sure. I can try to implement it. I have a very busy weekend, so if that's not a problem I can start working on it on Monday. I imagine you are going to be using it for your Particle Filter, right?
